name: Python package
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - dev
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - name: Get the code
            uses: actions/checkout@v4
          - name: Run tests
            run: |
              pip install pytest
              pytest -vv
          - name: Run the code
            run: |
              echo "Test"
              echo "$GITHUB_REF"
              echo "Commit ${{ github.sha }}"
              echi ${{ github.repository}}
              echo ${{ github.ref }}
              echo "Test"
              python app.py
    checks:
        name: Checking
        uses: ./.github/workflows/checks.yaml
        with:
            input_name: Bartek
